name: Check published links
on:
  workflow_call:
  # Uncomment waar je de workflow gebruikt
  # schedule:
    # Run on Mondays at 5:45 UTC
    # - cron: '45 5 * * 1'

jobs:
  link-checker:
    name: Check published links
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'Logius-standaarden' && github.repository != 'Logius-standaarden/ReSpec-template' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install muffet
        run: brew install muffet
      - name: Check published documents
        run: |
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/compute-published-url.js
          PUBLISHED_DOMAIN=$(node compute-published-url.js)
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/run-muffet.sh
          bash run-muffet.sh https://gitdocumentatie.logius.nl/publicatie/$PUBLISHED_DOMAIN > muffet.json || true
      - name: Collect broken links
        id: collect-broken-links
        run: |
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/muffet-json.py
          python muffet-json.py
          if [ -f "links.md" ]; then
            echo "has-errors=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Send email
        if: steps.collect-broken-links.outputs.has-errors != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Broken links on gitdocumentatie voor ${{ github.repository }}
          to: ${{secrets.MAIL_RECIPIENTS}}
          from: Standaarden Bot
          html_body: file://links.md
          ignore_cert: true
          convert_markdown: true
